title: "Yuukoの小屋"
subtitle: ""
description: "Yuuko 的个人博客"
keywords:
author: "Yuuko"
language: zh-CN
timezone: "Asia/Shanghai"

url: https://yuukowww.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true
  trailing_html: true

source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

new_post_name: :title.md
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: false

index_generator:
  path: ""
  per_page: 10
  order_by: -date

default_category: uncategorized
category_map:
tag_map:

meta_generator: true

date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: "mtime"

per_page: 10
pagination_dir: page

include:
exclude:
ignore:

theme: shokax

deploy:
  type: git
  repo: https://github.com/Yuukowww/Yuukowww.github.io
  branch: gh-pages
  message: "Site updated: {{ now('YYYY-MM-DD HH:mm:ss') }}"

feed:
  type:
    - rss2
    - atom
    - json
  path:
    - rss.xml
    - atom.xml
    - feed.json
  limit: 20

markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: false
    quotes: "“”‘’"

tikzjax:
  every_page: false
  append_css: true
  font_css_url: "https://cdn.jsdelivr.net/npm/node-tikzjax@latest/css/fonts.css"
